// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAsmazTDktHz827XhkbHFbkmFQLrrk15Y',
    appId: '1:753758815668:web:f239e4e29d20bbfc029ee1',
    messagingSenderId: '753758815668',
    projectId: 'organizador-multiplataforma-g',
    authDomain: 'organizador-multiplataforma-g.firebaseapp.com',
    storageBucket: 'organizador-multiplataforma-g.firebasestorage.app',
    measurementId: 'G-7FF3F7W2D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX82jQdFzbmrwfsGxVY2Qh80pTf4anthg',
    appId: '1:753758815668:android:8bf4dcb5a4deb850029ee1',
    messagingSenderId: '753758815668',
    projectId: 'organizador-multiplataforma-g',
    storageBucket: 'organizador-multiplataforma-g.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgFzDQzGZNHCdVIhJ6w-j0M0xKTTacLW4',
    appId: '1:753758815668:ios:ab79f3e8e3b963cc029ee1',
    messagingSenderId: '753758815668',
    projectId: 'organizador-multiplataforma-g',
    storageBucket: 'organizador-multiplataforma-g.firebasestorage.app',
    iosBundleId: 'com.example.omg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgFzDQzGZNHCdVIhJ6w-j0M0xKTTacLW4',
    appId: '1:753758815668:ios:ab79f3e8e3b963cc029ee1',
    messagingSenderId: '753758815668',
    projectId: 'organizador-multiplataforma-g',
    storageBucket: 'organizador-multiplataforma-g.firebasestorage.app',
    iosBundleId: 'com.example.omg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAsmazTDktHz827XhkbHFbkmFQLrrk15Y',
    appId: '1:753758815668:web:ce8376201c441ee2029ee1',
    messagingSenderId: '753758815668',
    projectId: 'organizador-multiplataforma-g',
    authDomain: 'organizador-multiplataforma-g.firebaseapp.com',
    storageBucket: 'organizador-multiplataforma-g.firebasestorage.app',
    measurementId: 'G-SW65SRQQFV',
  );
}
